# Project 1: Data Cleaning and Preparation

## Objective
The objective of this project is to clean and prepare a raw dataset by identifying missing values, checking for duplicate records, validating data formats, and ensuring data quality before analysis.

### Tasks Performed
- Dataset Inspection
- Missing Value Analysis
- Duplicate Record Detection
- Data Type Validation
- Data Cleaning
- Final Data Quality Verification

In [1]:
import pandas as pd
import numpy as np

## load The Dataset

In [2]:
df = pd.read_excel("Dataset for Data Analytics.xlsx")
df

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,2024-08-23,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,2023-10-15,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,ORD201195,2024-06-20,C21126,Desk,1,107.04,392 Main St,Credit Card,Cancelled,TRK38009181,6,FREESHIP,Google,107.04
1196,ORD201196,2024-03-04,C20095,Monitor,2,662.53,778 Main St,Online,Cancelled,TRK69207593,5,NaN,Facebook,1325.06
1197,ORD201197,2023-07-13,C79674,Tablet,2,436.84,275 Main St,Online,Delivered,TRK88039356,2,FREESHIP,Instagram,873.68
1198,ORD201198,2024-08-22,C64753,Chair,4,262.52,509 Main St,Debit Card,Cancelled,TRK71683331,4,WINTER15,Instagram,1050.08
1199,ORD201199,2023-06-11,C57502,Tablet,4,560.58,201 Main St,Gift Card,Returned,TRK51116746,6,SAVE10,Referral,2242.32

# Step 1: Dataset Overview

In this step, we examine the structure of the dataset, including the number of rows and columns, column names, and data types. This helps us understand the dataset before performing any cleaning operations.

### Display First Five Records

In [6]:
df.head()

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,2024-08-23,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,2023-10-15,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04

In [8]:
print("Dataset Shape:", df.shape)

Dataset Shape: (1200, 14)

In [9]:
print("\nNumber of Rows:", df.shape[0])
print("Number of Columns:", df.shape[1])

Number of Rows: 1200
Number of Columns: 14

### Column Names

In [10]:
print(df.columns.tolist())

['OrderID', 'Date', 'CustomerID', 'Product', 'Quantity', 'UnitPrice', 'ShippingAddress', 'PaymentMethod', 'OrderStatus', 'TrackingNumber', 'ItemsInCart', 'CouponCode', 'ReferralSource', 'TotalPrice']

### Data Types Information

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   OrderID          1200 non-null   object
 1   Date             1200 non-null   datetime64[ns]
 2   CustomerID       1200 non-null   object
 3   Product          1200 non-null   object
 4   Quantity         1200 non-null   int64
 5   UnitPrice        1200 non-null   float64
 6   ShippingAddress  1200 non-null   object
 7   PaymentMethod    1200 non-null   object
 8   OrderStatus      1200 non-null   object
 9   TrackingNumber   1200 non-null   object
 10  ItemsInCart      1200 non-null   int64
 11  CouponCode       891 non-null    object
 12  ReferralSource   1200 non-null   object
 13  TotalPrice       1200 non-null   float64
dtypes: datetime64[ns](1), float64(2), int64(2), object(9)
memory usage: 131.4+ KB

# Step 2: Missing Value Analysis

Missing values can affect data quality and analytical results. Therefore, we identify all missing values present in the dataset and calculate their frequency for each column.

### Count Missing Values

In [13]:
missing_values = df.isnull().sum()

print("Missing Values in Each Column")
print(missing_values)

Missing Values in Each Column
OrderID              0
Date                 0
CustomerID           0
Product              0
Quantity             0
UnitPrice            0
ShippingAddress      0
PaymentMethod        0
OrderStatus          0
TrackingNumber       0
ItemsInCart          0
CouponCode         309
ReferralSource       0
TotalPrice           0
dtype: int64

### Missing Value Percentage

In [14]:
missing_percentage = (df.isnull().sum() / len(df)) * 100

missing_summary = pd.DataFrame({
    'Missing Count': df.isnull().sum(),
    'Missing Percentage': missing_percentage
})

missing_summary

                 Missing Count  Missing Percentage
OrderID                      0                0.00
Date                         0                0.00
CustomerID                   0                0.00
Product                      0                0.00
Quantity                     0                0.00
UnitPrice                    0                0.00
ShippingAddress              0                0.00
PaymentMethod                0                0.00
OrderStatus                  0                0.00
TrackingNumber               0                0.00
ItemsInCart                  0                0.00
CouponCode                 309               25.75
ReferralSource               0                0.00
TotalPrice                   0                0.00

### Columns Containing Missing Values Only

In [15]:
missing_summary[missing_summary['Missing Count'] > 0]

            Missing Count  Missing Percentage
CouponCode            309               25.75

# Step 3: Handling Missing Values

The dataset contains missing values only in the CouponCode column. These missing values do not represent data entry errors; rather, they indicate that no coupon was applied during the transaction.

To preserve all transaction records and improve data consistency, missing values in the CouponCode column are replaced with "No Coupon".

In [16]:
# Replace Missing Coupon Codes

df['CouponCode'] = df['CouponCode'].fillna('No Coupon')

In [17]:
# Verify Missing Values After Treatment

df['CouponCode'].isnull().sum()

np.int64(0)

### Result

All missing values in the CouponCode column were successfully handled by replacing null entries with "No Coupon".

Remaining Missing Values: 0

# Step 4: Duplicate Record Detection

Duplicate records can lead to inaccurate analysis and misleading results. Therefore, the dataset is checked for both complete duplicate rows and duplicate Order IDs.

In [18]:
# Check Complete Duplicate Rows
duplicate_rows = df.duplicated().sum()

print("Duplicate Rows:", duplicate_rows)

Duplicate Rows: 0

In [19]:
# Check Duplicate Order IDs
duplicate_order_ids = df['OrderID'].duplicated().sum()

print("Duplicate Order IDs:", duplicate_order_ids)

Duplicate Order IDs: 0

# Step 5: Date Format Validation

Date fields must follow a consistent format for accurate analysis and reporting.

In this step, the Date column is converted into a proper datetime format and checked for invalid or incorrectly formatted values.

In [20]:
# Check Current Data Type of Date Column

print(df['Date'].dtype)

datetime64[ns]

In [21]:
# Convert Date Column to Datetime Format

df['Date'] = pd.to_datetime(df['Date'], errors='coerce')

In [22]:
# Check Invalid Dates

invalid_dates = df['Date'].isnull().sum()

print("Invalid Dates:", invalid_dates)

Invalid Dates: 0

### Result

All dates were successfully converted into datetime format.

Number of Invalid Dates Found: 0

Therefore, the dataset contains no incorrectly formatted date values.

# Step 6: Data Type Validation

The dataset contains numerical, categorical, and date variables. Data types are verified to ensure each column is stored in an appropriate format for analysis.

In [23]:
# Display Data Types

df.dtypes

OrderID                    object
Date               datetime64[ns]
CustomerID                 object
Product                    object
Quantity                    int64
UnitPrice                 float64
ShippingAddress            object
PaymentMethod              object
OrderStatus                object
TrackingNumber             object
ItemsInCart                 int64
CouponCode                 object
ReferralSource             object
TotalPrice                float64
dtype: object

# Step 7: Data Consistency Validation

To ensure data accuracy, the relationship between Quantity, UnitPrice, and TotalPrice is verified.

Expected Formula:

TotalPrice = Quantity × UnitPrice

Any mismatch would indicate a potential data quality issue.

In [24]:
# Calculate Expected Total Price

df['CalculatedTotal'] = df['Quantity'] * df['UnitPrice']

In [25]:
# Find Mismatched Records

mismatch_count = (
    round(df['CalculatedTotal'], 2) !=
    round(df['TotalPrice'], 2)
).sum()

print("Total Price Mismatches:", mismatch_count)

Total Price Mismatches: 0

### Result

The TotalPrice values are consistent with the Quantity and UnitPrice values.

Number of Mismatched Records: 0

Therefore, no calculation errors were detected in the dataset.

In [27]:
# Final Missing Values Check

print(df.isnull().sum())

OrderID            0
Date               0
CustomerID         0
Product            0
Quantity           0
UnitPrice          0
ShippingAddress    0
PaymentMethod      0
OrderStatus        0
TrackingNumber     0
ItemsInCart        0
CouponCode         0
ReferralSource     0
TotalPrice         0
CalculatedTotal    0
dtype: int64

# Step 8: Final Data Quality Verification

After performing all cleaning operations, a final quality check is conducted to ensure:

- No missing values remain
- No duplicate records exist
- No duplicate Order IDs exist
- No invalid date values exist
- TotalPrice values are correctly calculated

This confirms that the dataset is clean and ready for analysis.